### ISSUE TITLE
Добавить возможность изменения поля displayName у user

### ISSUE THREAD

**Issue by j-avdeev** [imercury13/ya360#38]
Здравствуйте.

У user кроме атрибута **name** есть ещё **displayName** (см. подробнее https://yandex.ru/dev/api360/doc/ref/UserService/UserService_Update.html),
кроме прочего его на сегодняшний момент (2024.02.21) нельзя изменить через веб-интерфейс.

Поэтому очень актуально иметь возможность менять **displayName**

Заранее спасибо.

**Comment by imercury13** [comment]
Добрый день!
Спасибо за проявленный интерес, постараюсь добавить эту возможность в течении нескольких дней

**Comment by imercury13** [comment]
Готово
