### ISSUE TITLE
Не дает менять displayName

### ISSUE THREAD

**Issue by sc16me** [imercury13/ya360#46]
Не дает менять displayName
Права выданы, ошибок нет( Просто висит.

![Снимок экрана 2024-05-28 в 16 53 17](https://github.com/imercury13/ya360/assets/1618809/4e2fc72b-6544-41a3-a7ed-e16ca913d3ad)
![Снимок экрана 2024-05-28 в 16 58 15](https://github.com/imercury13/ya360/assets/1618809/e3db7689-2855-4169-bac9-21ded09c0932)

**Comment by imercury13** [comment]
Укажите пожалуйста версию. Должна быть 3.6.1

**Comment by sc16me** [comment]
Версия 3.6.1

**Comment by imercury13** [comment]
![Screenshot_20240529_122936](https://github.com/imercury13/ya360/assets/108464106/184db429-a352-4661-8a5e-0a7c09c20fcb)

Пока не удается воспроизвести зависание

**Comment by sc16me** [comment]
Возможно дело в яндексе, хотя все правда выданы, напрямую через curl тоже не работает. В данный момент жду ответа от их техподдержки.

**Comment by imercury13** [comment]
На другой машине удалось воспроизвести. Спасибо! Буду смотреть детально

**Comment by imercury13** [comment]
Обновитесь до версии 3.6.2

**Comment by sc16me** [comment]
Спасибо, все на 3.6.2 все работает без проблем!
