### ISSUE TITLE
Ошибка  No required scope 

### ISSUE THREAD

**Issue by ruslanin** [imercury13/ya360#47]
Пытаюсь получить список сотрудников организации 

команда ya360 user show-all выдает ошибку  No required scope

Приложение настроено по инструкции

**Comment by imercury13** [comment]
Добрый день!
К сожалению, посмотреть удастся только после 8 июля... но я обязательно посмотрю. Хотя очень странная ошибка, такое ощущение, что не всех прав хватает...

**Comment by imercury13** [comment]
No required scope - все же из-за недостаточных прав. Приложение нужно регистрировать на адрес администратора.
Для ya360 нужно выбирать все права на все подразделы, касающиеся функционала yandex 360 для бизнеса

**Comment by imercury13** [comment]
directory:write_organization
directory:manage_dns
ya360_admin:mail_write_antispam_settings
ya360_security:audit_log_disk
ya360_security:audit_log_mail
ya360_security:domain_2fa_write
ya360_security:domain_sessions_write
ya360_security:domain_passwords_write
directory:write_groups
directory:write_domains
ya360_admin:mail_write_shared_mailbox_inventory
ya360_admin:mail_write_user_settings
directory:write_organization
directory:write_departments
ya360_admin:mail_write_routing_rules
ya360_security:service_applications_write
directory:write_users
